/* $svelte\fluent-svelte-raw\MenuFlyout\MenuFlyoutSurface.svelte generated by Svelte v3.46.4 */
import {
	SvelteComponent,
	append,
	append_styles,
	assign,
	attr,
	binding_callbacks,
	compute_rest_props,
	create_slot,
	detach,
	element as element_1,
	exclude_internal_props,
	get_all_dirty_from_scope,
	get_slot_changes,
	get_spread_update,
	init,
	insert,
	listen,
	safe_not_equal,
	set_attributes,
	toggle_class,
	transition_in,
	transition_out,
	update_slot_base
} from "mth://.svelte/internal";

function add_css(target) {
	append_styles(target, "svelte-1qibxfp", "@-webkit-keyframes svelte-1qibxfp-menu-open{0%{transform:translateY(var(--fds-menu-flyout-transition-offset,-50%))}to{transform:none}}@keyframes svelte-1qibxfp-menu-open{0%{transform:translateY(var(--fds-menu-flyout-transition-offset,-50%))}to{transform:none}}@-webkit-keyframes svelte-1qibxfp-menu-shadow{0%{box-shadow:none}to{box-shadow:var(--fds-flyout-shadow)}}@keyframes svelte-1qibxfp-menu-shadow{0%{box-shadow:none}to{box-shadow:var(--fds-flyout-shadow)}}.menu-flyout.svelte-1qibxfp{-webkit-animation:svelte-1qibxfp-menu-open var(--fds-control-normal-duration) var(--fds-control-fast-out-slow-in-easing),svelte-1qibxfp-menu-shadow var(--fds-control-fast-duration) var(--fds-control-fast-out-slow-in-easing) var(--fds-control-normal-duration) forwards;animation:svelte-1qibxfp-menu-open var(--fds-control-normal-duration) var(--fds-control-fast-out-slow-in-easing),svelte-1qibxfp-menu-shadow var(--fds-control-fast-duration) var(--fds-control-fast-out-slow-in-easing) var(--fds-control-normal-duration) forwards;background-clip:padding-box;background-color:var(--fds-solid-background-quarternary);border:1px solid var(--fds-surface-stroke-flyout);border-radius:var(--fds-overlay-corner-radius);box-sizing:border-box;color:var(--fds-text-primary);display:flex;flex-direction:column;font-family:var(--fds-font-family-text);font-size:var(--fds-body-font-size);font-weight:400;line-height:20px;margin:0;max-block-size:100vh;max-inline-size:100%;min-inline-size:120px;padding:0;padding-block:2px;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.menu-flyout-surface-container.svelte-1qibxfp{overflow:hidden}");
}

function create_fragment(ctx) {
	let div;
	let ul;
	let ul_class_value;
	let div_style_value;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	let ul_levels = [
		{
			class: ul_class_value = "menu-flyout " + /*className*/ ctx[1]
		},
		/*$$restProps*/ ctx[3]
	];

	let ul_data = {};

	for (let i = 0; i < ul_levels.length; i += 1) {
		ul_data = assign(ul_data, ul_levels[i]);
	}

	return {
		c() {
			div = element_1("div");
			ul = element_1("ul");
			if (default_slot) default_slot.c();
			set_attributes(ul, ul_data);
			toggle_class(ul, "svelte-1qibxfp", true);
			attr(div, "class", "menu-flyout-surface-container svelte-1qibxfp");

			attr(div, "style", div_style_value = /*animationComplete*/ ctx[2]
			? "overflow: visible;"
			: undefined);
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, ul);

			if (default_slot) {
				default_slot.m(ul, null);
			}

			/*ul_binding*/ ctx[7](ul);
			current = true;

			if (!mounted) {
				dispose = listen(ul, "animationend", /*animationend_handler*/ ctx[6], { once: true });
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 16)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[4],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[4])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[4], dirty, null),
						null
					);
				}
			}

			set_attributes(ul, ul_data = get_spread_update(ul_levels, [
				(!current || dirty & /*className*/ 2 && ul_class_value !== (ul_class_value = "menu-flyout " + /*className*/ ctx[1])) && { class: ul_class_value },
				dirty & /*$$restProps*/ 8 && /*$$restProps*/ ctx[3]
			]));

			toggle_class(ul, "svelte-1qibxfp", true);

			if (!current || dirty & /*animationComplete*/ 4 && div_style_value !== (div_style_value = /*animationComplete*/ ctx[2]
			? "overflow: visible;"
			: undefined)) {
				attr(div, "style", div_style_value);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			if (default_slot) default_slot.d(detaching);
			/*ul_binding*/ ctx[7](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	const omit_props_names = ["class","element"];
	let $$restProps = compute_rest_props($$props, omit_props_names);
	let { $$slots: slots = {}, $$scope } = $$props;
	let { class: className = "" } = $$props;
	let { element = null } = $$props;
	let animationComplete = false;
	const animationend_handler = () => $$invalidate(2, animationComplete = true);

	function ul_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			element = $$value;
			$$invalidate(0, element);
		});
	}

	$$self.$$set = $$new_props => {
		$$props = assign(assign({}, $$props), exclude_internal_props($$new_props));
		$$invalidate(3, $$restProps = compute_rest_props($$props, omit_props_names));
		if ('class' in $$new_props) $$invalidate(1, className = $$new_props.class);
		if ('element' in $$new_props) $$invalidate(0, element = $$new_props.element);
		if ('$$scope' in $$new_props) $$invalidate(4, $$scope = $$new_props.$$scope);
	};

	return [
		element,
		className,
		animationComplete,
		$$restProps,
		$$scope,
		slots,
		animationend_handler,
		ul_binding
	];
}

class MenuFlyoutSurface extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { class: 1, element: 0 }, add_css);
	}
}

export default MenuFlyoutSurface;