/* $svelte\fluent-svelte-raw\MenuBar\MenuBarItem.svelte generated by Svelte v3.46.4 */
import {
	SvelteComponent,
	action_destroyer,
	add_flush_callback,
	append,
	append_styles,
	assign,
	attr,
	bind,
	binding_callbacks,
	check_outros,
	component_subscribe,
	compute_rest_props,
	compute_slots,
	create_component,
	create_slot,
	destroy_component,
	detach,
	element as element_1,
	exclude_internal_props,
	get_all_dirty_from_scope,
	get_slot_changes,
	get_spread_update,
	group_outros,
	init,
	insert,
	listen,
	mount_component,
	run_all,
	safe_not_equal,
	self,
	set_attributes,
	set_store_value,
	space,
	toggle_class,
	transition_in,
	transition_out,
	update_slot_base
} from "mth://.svelte/internal";

import { currentMenu } from "./flyoutState";
import { tabbable } from "../tabbable";
import { createEventDispatcher, getContext, setContext } from "mth://.svelte/internal";
import { get_current_component } from "mth://.svelte/internal";

import {
	createEventForwarder,
	arrowNavigation,
	externalMouseEvents,
	uid
} from "../internal";

import MenuFlyoutSurface from "../MenuFlyout/MenuFlyoutSurface.svelte";

function add_css(target) {
	append_styles(target, "svelte-1r3ld34", ".menu-bar-item.svelte-1r3ld34{align-items:center;background-color:var(--fds-subtle-fill-transparent);border-radius:var(--fds-control-corner-radius);color:var(--fds-text-primary);cursor:default;display:inline-flex;font-family:var(--fds-font-family-text);font-size:var(--fds-body-font-size);font-weight:400;line-height:20px;margin:4px;padding:5px 11px;position:relative;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.menu-bar-item.svelte-1r3ld34:hover{background-color:var(--fds-subtle-fill-secondary)}.menu-bar-item.svelte-1r3ld34:active,.menu-bar-item[aria-expanded=true].svelte-1r3ld34{background-color:var(--fds-subtle-fill-tertiary)}.menu-bar-item.svelte-1r3ld34:active:hover,.menu-bar-item[aria-expanded=true].svelte-1r3ld34:hover{background-color:var(--fds-subtle-fill-secondary)}.menu-bar-item.svelte-1r3ld34:active{color:var(--fds-text-secondary)}.menu-bar-item.disabled.svelte-1r3ld34{background-color:var(--fds-subtle-fill-disabled)!important;color:var(--fds-text-disabled)}.menu-flyout-anchor.svelte-1r3ld34{inset-block-start:100%;inset-inline-start:0;position:absolute;z-index:10000}");
}

const get_flyout_slot_changes = dirty => ({});
const get_flyout_slot_context = ctx => ({});

// (104:1) {#if $$slots.flyout && open && !disabled}
function create_if_block(ctx) {
	let div;
	let menuflyoutsurface;
	let updating_element;
	let arrowNavigation_action;
	let externalMouseEvents_action;
	let current;
	let mounted;
	let dispose;

	function menuflyoutsurface_element_binding(value) {
		/*menuflyoutsurface_element_binding*/ ctx[18](value);
	}

	let menuflyoutsurface_props = {
		$$slots: { default: [create_default_slot] },
		$$scope: { ctx }
	};

	if (/*menuElement*/ ctx[3] !== void 0) {
		menuflyoutsurface_props.element = /*menuElement*/ ctx[3];
	}

	menuflyoutsurface = new MenuFlyoutSurface({ props: menuflyoutsurface_props });
	binding_callbacks.push(() => bind(menuflyoutsurface, 'element', menuflyoutsurface_element_binding));
	/*menuflyoutsurface_binding*/ ctx[19](menuflyoutsurface);

	return {
		c() {
			div = element_1("div");
			create_component(menuflyoutsurface.$$.fragment);
			attr(div, "class", "menu-flyout-anchor svelte-1r3ld34");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			mount_component(menuflyoutsurface, div, null);
			/*div_binding*/ ctx[21](div);
			current = true;

			if (!mounted) {
				dispose = [
					action_destroyer(arrowNavigation_action = arrowNavigation.call(null, div, { preventTab: true })),
					action_destroyer(externalMouseEvents_action = externalMouseEvents.call(null, div, { type: "mousedown", stopPropagation: true })),
					listen(div, "outermousedown", /*outermousedown_handler*/ ctx[20])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			const menuflyoutsurface_changes = {};

			if (dirty & /*$$scope*/ 33554432) {
				menuflyoutsurface_changes.$$scope = { dirty, ctx };
			}

			if (!updating_element && dirty & /*menuElement*/ 8) {
				updating_element = true;
				menuflyoutsurface_changes.element = /*menuElement*/ ctx[3];
				add_flush_callback(() => updating_element = false);
			}

			menuflyoutsurface.$set(menuflyoutsurface_changes);
		},
		i(local) {
			if (current) return;
			transition_in(menuflyoutsurface.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(menuflyoutsurface.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			/*menuflyoutsurface_binding*/ ctx[19](null);
			destroy_component(menuflyoutsurface);
			/*div_binding*/ ctx[21](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (112:3) <MenuFlyoutSurface bind:element={menuElement} bind:this={menu}>
function create_default_slot(ctx) {
	let current;
	const flyout_slot_template = /*#slots*/ ctx[17].flyout;
	const flyout_slot = create_slot(flyout_slot_template, ctx, /*$$scope*/ ctx[25], get_flyout_slot_context);

	return {
		c() {
			if (flyout_slot) flyout_slot.c();
		},
		m(target, anchor) {
			if (flyout_slot) {
				flyout_slot.m(target, anchor);
			}

			current = true;
		},
		p(ctx, dirty) {
			if (flyout_slot) {
				if (flyout_slot.p && (!current || dirty & /*$$scope*/ 33554432)) {
					update_slot_base(
						flyout_slot,
						flyout_slot_template,
						ctx,
						/*$$scope*/ ctx[25],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[25])
						: get_slot_changes(flyout_slot_template, /*$$scope*/ ctx[25], dirty, get_flyout_slot_changes),
						get_flyout_slot_context
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(flyout_slot, local);
			current = true;
		},
		o(local) {
			transition_out(flyout_slot, local);
			current = false;
		},
		d(detaching) {
			if (flyout_slot) flyout_slot.d(detaching);
		}
	};
}

function create_fragment(ctx) {
	let li;
	let t;
	let li_class_value;
	let li_tabindex_value;
	let li_aria_expanded_value;
	let li_aria_haspopup_value;
	let li_aria_controls_value;
	let forwardEvents_action;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[17].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[25], null);
	let if_block = /*$$slots*/ ctx[14].flyout && /*open*/ ctx[0] && !/*disabled*/ ctx[4] && create_if_block(ctx);

	let li_levels = [
		{
			class: li_class_value = "menu-bar-item " + /*className*/ ctx[5]
		},
		{ role: "menuitem" },
		{
			tabindex: li_tabindex_value = /*disabled*/ ctx[4] ? -1 : 0
		},
		{
			"aria-expanded": li_aria_expanded_value = /*$$slots*/ ctx[14].flyout && !/*disabled*/ ctx[4] && /*open*/ ctx[0]
		},
		{
			"aria-haspopup": li_aria_haspopup_value = /*$$slots*/ ctx[14].flyout && !/*disabled*/ ctx[4] && /*open*/ ctx[0]
		},
		{
			"aria-controls": li_aria_controls_value = /*$$slots*/ ctx[14].flyout && !/*disabled*/ ctx[4] && /*menuId*/ ctx[8]
		},
		/*$$restProps*/ ctx[15]
	];

	let li_data = {};

	for (let i = 0; i < li_levels.length; i += 1) {
		li_data = assign(li_data, li_levels[i]);
	}

	return {
		c() {
			li = element_1("li");
			if (default_slot) default_slot.c();
			t = space();
			if (if_block) if_block.c();
			set_attributes(li, li_data);
			toggle_class(li, "disabled", /*disabled*/ ctx[4]);
			toggle_class(li, "svelte-1r3ld34", true);
		},
		m(target, anchor) {
			insert(target, li, anchor);

			if (default_slot) {
				default_slot.m(li, null);
			}

			append(li, t);
			if (if_block) if_block.m(li, null);
			/*li_binding*/ ctx[22](li);
			current = true;

			if (!mounted) {
				dispose = [
					listen(window, "keydown", /*handleEscapeKey*/ ctx[10]),
					action_destroyer(forwardEvents_action = /*forwardEvents*/ ctx[7].call(null, li)),
					listen(li, "keydown", /*keydown_handler*/ ctx[23]),
					listen(li, "keydown", self(/*handleKeyDown*/ ctx[12])),
					listen(li, "focus", /*handleFocus*/ ctx[13]),
					listen(li, "mousedown", /*mousedown_handler*/ ctx[24]),
					listen(li, "mouseenter", /*handleMouseEnter*/ ctx[11])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 33554432)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[25],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[25])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[25], dirty, null),
						null
					);
				}
			}

			if (/*$$slots*/ ctx[14].flyout && /*open*/ ctx[0] && !/*disabled*/ ctx[4]) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*$$slots, open, disabled*/ 16401) {
						transition_in(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					transition_in(if_block, 1);
					if_block.m(li, null);
				}
			} else if (if_block) {
				group_outros();

				transition_out(if_block, 1, 1, () => {
					if_block = null;
				});

				check_outros();
			}

			set_attributes(li, li_data = get_spread_update(li_levels, [
				(!current || dirty & /*className*/ 32 && li_class_value !== (li_class_value = "menu-bar-item " + /*className*/ ctx[5])) && { class: li_class_value },
				{ role: "menuitem" },
				(!current || dirty & /*disabled*/ 16 && li_tabindex_value !== (li_tabindex_value = /*disabled*/ ctx[4] ? -1 : 0)) && { tabindex: li_tabindex_value },
				(!current || dirty & /*$$slots, disabled, open*/ 16401 && li_aria_expanded_value !== (li_aria_expanded_value = /*$$slots*/ ctx[14].flyout && !/*disabled*/ ctx[4] && /*open*/ ctx[0])) && { "aria-expanded": li_aria_expanded_value },
				(!current || dirty & /*$$slots, disabled, open*/ 16401 && li_aria_haspopup_value !== (li_aria_haspopup_value = /*$$slots*/ ctx[14].flyout && !/*disabled*/ ctx[4] && /*open*/ ctx[0])) && { "aria-haspopup": li_aria_haspopup_value },
				(!current || dirty & /*$$slots, disabled*/ 16400 && li_aria_controls_value !== (li_aria_controls_value = /*$$slots*/ ctx[14].flyout && !/*disabled*/ ctx[4] && /*menuId*/ ctx[8])) && { "aria-controls": li_aria_controls_value },
				dirty & /*$$restProps*/ 32768 && /*$$restProps*/ ctx[15]
			]));

			toggle_class(li, "disabled", /*disabled*/ ctx[4]);
			toggle_class(li, "svelte-1r3ld34", true);
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			transition_in(if_block);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			transition_out(if_block);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(li);
			if (default_slot) default_slot.d(detaching);
			if (if_block) if_block.d();
			/*li_binding*/ ctx[22](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	const omit_props_names = ["open","disabled","class","element","anchorElement","menuElement"];
	let $$restProps = compute_rest_props($$props, omit_props_names);
	let $currentMenu;
	component_subscribe($$self, currentMenu, $$value => $$invalidate(16, $currentMenu = $$value));
	let { $$slots: slots = {}, $$scope } = $$props;
	const $$slots = compute_slots(slots);
	let { open = false } = $$props;
	let { disabled = false } = $$props;
	let { class: className = "" } = $$props;
	let { element = null } = $$props;
	let { anchorElement = null } = $$props;
	let { menuElement = null } = $$props;
	let menu;
	const forwardEvents = createEventForwarder(get_current_component(), ["open", "close", "select"]);
	const dispatch = createEventDispatcher();
	const menuId = uid("fds-menu-flyout-anchor-");
	const handleSideNavigation = getContext("sideNavigation");

	function focusFirstItem() {
		if (open && menu && tabbable(menuElement).length > 0) tabbable(menuElement)[0].focus();
	}

	function handleEscapeKey({ key }) {
		if (key === "Escape") $$invalidate(0, open = false);
	}

	function handleMouseEnter() {
		if ($currentMenu && $$slots.flyout) {
			set_store_value(currentMenu, $currentMenu = menu, $currentMenu);
			$$invalidate(0, open = true);
		}
	}

	function handleKeyDown({ key }) {
		if (key === "Enter" || key === " ") {
			event.preventDefault();
			$$invalidate(0, open = !open);
		}
	}

	function handleFocus() {
		if (open) {
			focusFirstItem();
		} else if ($currentMenu) {
			set_store_value(currentMenu, $currentMenu = menu, $currentMenu);
			$$invalidate(0, open = true);
		}
	}

	setContext("closeFlyout", event => {
		dispatch("select");
		event.stopPropagation();
		$$invalidate(0, open = false);
	});

	function menuflyoutsurface_element_binding(value) {
		menuElement = value;
		$$invalidate(3, menuElement);
	}

	function menuflyoutsurface_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			menu = $$value;
			$$invalidate(6, menu);
		});
	}

	const outermousedown_handler = () => $$invalidate(0, open = false);

	function div_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			anchorElement = $$value;
			$$invalidate(2, anchorElement);
		});
	}

	function li_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			element = $$value;
			$$invalidate(1, element);
		});
	}

	const keydown_handler = event => handleSideNavigation(event, element);
	const mousedown_handler = () => $$invalidate(0, open = !open);

	$$self.$$set = $$new_props => {
		$$props = assign(assign({}, $$props), exclude_internal_props($$new_props));
		$$invalidate(15, $$restProps = compute_rest_props($$props, omit_props_names));
		if ('open' in $$new_props) $$invalidate(0, open = $$new_props.open);
		if ('disabled' in $$new_props) $$invalidate(4, disabled = $$new_props.disabled);
		if ('class' in $$new_props) $$invalidate(5, className = $$new_props.class);
		if ('element' in $$new_props) $$invalidate(1, element = $$new_props.element);
		if ('anchorElement' in $$new_props) $$invalidate(2, anchorElement = $$new_props.anchorElement);
		if ('menuElement' in $$new_props) $$invalidate(3, menuElement = $$new_props.menuElement);
		if ('$$scope' in $$new_props) $$invalidate(25, $$scope = $$new_props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*menu*/ 64) {
			$: if (menu) {
				focusFirstItem();
				set_store_value(currentMenu, $currentMenu = menu, $currentMenu);
			} else {
				set_store_value(currentMenu, $currentMenu = null, $currentMenu);
			}
		}

		if ($$self.$$.dirty & /*$currentMenu, menu*/ 65600) {
			$: if ($currentMenu !== menu) $$invalidate(0, open = false);
		}

		if ($$self.$$.dirty & /*menu, element*/ 66) {
			$: if (!menu && element) element.focus();
		}

		if ($$self.$$.dirty & /*open, disabled*/ 17) {
			$: if ($$slots.flyout && open && !disabled) {
				if (open) {
					dispatch("open");
				} else {
					dispatch("close");
				}
			}
		}
	};

	return [
		open,
		element,
		anchorElement,
		menuElement,
		disabled,
		className,
		menu,
		forwardEvents,
		menuId,
		handleSideNavigation,
		handleEscapeKey,
		handleMouseEnter,
		handleKeyDown,
		handleFocus,
		$$slots,
		$$restProps,
		$currentMenu,
		slots,
		menuflyoutsurface_element_binding,
		menuflyoutsurface_binding,
		outermousedown_handler,
		div_binding,
		li_binding,
		keydown_handler,
		mousedown_handler,
		$$scope
	];
}

class MenuBarItem extends SvelteComponent {
	constructor(options) {
		super();

		init(
			this,
			options,
			instance,
			create_fragment,
			safe_not_equal,
			{
				open: 0,
				disabled: 4,
				class: 5,
				element: 1,
				anchorElement: 2,
				menuElement: 3
			},
			add_css
		);
	}
}

export default MenuBarItem;