/* $svelte\fluent-svelte-raw\ContextMenu\ContextMenu.svelte generated by Svelte v3.46.4 */
import {
	SvelteComponent,
	action_destroyer,
	add_flush_callback,
	append,
	append_styles,
	assign,
	attr,
	bind,
	binding_callbacks,
	bubble,
	check_outros,
	compute_rest_props,
	create_component,
	create_slot,
	destroy_component,
	detach,
	element,
	exclude_internal_props,
	get_all_dirty_from_scope,
	get_slot_changes,
	get_spread_object,
	get_spread_update,
	globals,
	group_outros,
	init,
	insert,
	listen,
	mount_component,
	prevent_default,
	run_all,
	safe_not_equal,
	set_style,
	space,
	stop_propagation,
	transition_in,
	transition_out,
	update_slot_base
} from "mth://.svelte/internal";

const { window: window_1 } = globals;
import { createEventDispatcher, setContext } from "mth://.svelte/internal";
import { externalMouseEvents, arrowNavigation } from "../internal";
import { tabbable } from "../tabbable";
import MenuFlyoutSurface from "../MenuFlyout/MenuFlyoutSurface.svelte";

function add_css(target) {
	append_styles(target, "svelte-s5j1tt", ".context-menu-wrapper.svelte-s5j1tt{display:contents}.context-menu-anchor.svelte-s5j1tt{position:fixed;z-index:10000}");
}

const get_flyout_slot_changes = dirty => ({});
const get_flyout_slot_context = ctx => ({});

// (71:1) {#if open}
function create_if_block(ctx) {
	let div;
	let menuflyoutsurface;
	let updating_element;
	let mountMenu_action;
	let arrowNavigation_action;
	let externalMouseEvents_action;
	let current;
	let mounted;
	let dispose;
	const menuflyoutsurface_spread_levels = [/*$$restProps*/ ctx[8]];

	function menuflyoutsurface_element_binding(value) {
		/*menuflyoutsurface_element_binding*/ ctx[14](value);
	}

	let menuflyoutsurface_props = {
		$$slots: { default: [create_default_slot] },
		$$scope: { ctx }
	};

	for (let i = 0; i < menuflyoutsurface_spread_levels.length; i += 1) {
		menuflyoutsurface_props = assign(menuflyoutsurface_props, menuflyoutsurface_spread_levels[i]);
	}

	if (/*menuElement*/ ctx[2] !== void 0) {
		menuflyoutsurface_props.element = /*menuElement*/ ctx[2];
	}

	menuflyoutsurface = new MenuFlyoutSurface({ props: menuflyoutsurface_props });
	/*menuflyoutsurface_binding*/ ctx[13](menuflyoutsurface);
	binding_callbacks.push(() => bind(menuflyoutsurface, 'element', menuflyoutsurface_element_binding));

	return {
		c() {
			div = element("div");
			create_component(menuflyoutsurface.$$.fragment);
			attr(div, "class", "context-menu-anchor svelte-s5j1tt");
			set_style(div, "top", /*menuPosition*/ ctx[5].y + "px");
			set_style(div, "left", /*menuPosition*/ ctx[5].x + "px");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			mount_component(menuflyoutsurface, div, null);
			/*div_binding*/ ctx[15](div);
			current = true;

			if (!mounted) {
				dispose = [
					action_destroyer(mountMenu_action = mountMenu.call(null, div)),
					action_destroyer(arrowNavigation_action = arrowNavigation.call(null, div, { preventTab: true })),
					action_destroyer(externalMouseEvents_action = externalMouseEvents.call(null, div, { type: "mousedown" })),
					listen(div, "contextmenu", stop_propagation(contextmenu_handler_1)),
					listen(div, "outermousedown", /*outermousedown_handler*/ ctx[16])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			const menuflyoutsurface_changes = (dirty & /*$$restProps*/ 256)
			? get_spread_update(menuflyoutsurface_spread_levels, [get_spread_object(/*$$restProps*/ ctx[8])])
			: {};

			if (dirty & /*$$scope*/ 262144) {
				menuflyoutsurface_changes.$$scope = { dirty, ctx };
			}

			if (!updating_element && dirty & /*menuElement*/ 4) {
				updating_element = true;
				menuflyoutsurface_changes.element = /*menuElement*/ ctx[2];
				add_flush_callback(() => updating_element = false);
			}

			menuflyoutsurface.$set(menuflyoutsurface_changes);

			if (!current || dirty & /*menuPosition*/ 32) {
				set_style(div, "top", /*menuPosition*/ ctx[5].y + "px");
			}

			if (!current || dirty & /*menuPosition*/ 32) {
				set_style(div, "left", /*menuPosition*/ ctx[5].x + "px");
			}
		},
		i(local) {
			if (current) return;
			transition_in(menuflyoutsurface.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(menuflyoutsurface.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			/*menuflyoutsurface_binding*/ ctx[13](null);
			destroy_component(menuflyoutsurface);
			/*div_binding*/ ctx[15](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (82:3) <MenuFlyoutSurface bind:this={menu} bind:element={menuElement} {...$$restProps}>
function create_default_slot(ctx) {
	let current;
	const flyout_slot_template = /*#slots*/ ctx[11].flyout;
	const flyout_slot = create_slot(flyout_slot_template, ctx, /*$$scope*/ ctx[18], get_flyout_slot_context);

	return {
		c() {
			if (flyout_slot) flyout_slot.c();
		},
		m(target, anchor) {
			if (flyout_slot) {
				flyout_slot.m(target, anchor);
			}

			current = true;
		},
		p(ctx, dirty) {
			if (flyout_slot) {
				if (flyout_slot.p && (!current || dirty & /*$$scope*/ 262144)) {
					update_slot_base(
						flyout_slot,
						flyout_slot_template,
						ctx,
						/*$$scope*/ ctx[18],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[18])
						: get_slot_changes(flyout_slot_template, /*$$scope*/ ctx[18], dirty, get_flyout_slot_changes),
						get_flyout_slot_context
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(flyout_slot, local);
			current = true;
		},
		o(local) {
			transition_out(flyout_slot, local);
			current = false;
		},
		d(detaching) {
			if (flyout_slot) flyout_slot.d(detaching);
		}
	};
}

function create_fragment(ctx) {
	let div;
	let t;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[11].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[18], null);
	let if_block = /*open*/ ctx[0] && create_if_block(ctx);

	return {
		c() {
			div = element("div");
			if (default_slot) default_slot.c();
			t = space();
			if (if_block) if_block.c();
			attr(div, "class", "context-menu-wrapper svelte-s5j1tt");
		},
		m(target, anchor) {
			insert(target, div, anchor);

			if (default_slot) {
				default_slot.m(div, null);
			}

			append(div, t);
			if (if_block) if_block.m(div, null);
			/*div_binding_1*/ ctx[17](div);
			current = true;

			if (!mounted) {
				dispose = [
					listen(window_1, "keydown", /*handleEscapeKey*/ ctx[7]),
					listen(div, "contextmenu", stop_propagation(prevent_default(/*handleContextMenu*/ ctx[6]))),
					listen(div, "contextmenu", /*contextmenu_handler*/ ctx[12])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 262144)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[18],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[18])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[18], dirty, null),
						null
					);
				}
			}

			if (/*open*/ ctx[0]) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*open*/ 1) {
						transition_in(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					transition_in(if_block, 1);
					if_block.m(div, null);
				}
			} else if (if_block) {
				group_outros();

				transition_out(if_block, 1, 1, () => {
					if_block = null;
				});

				check_outros();
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			transition_in(if_block);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			transition_out(if_block);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			if (default_slot) default_slot.d(detaching);
			if (if_block) if_block.d();
			/*div_binding_1*/ ctx[17](null);
			mounted = false;
			run_all(dispose);
		}
	};
}

function mountMenu(node) {
	document.body.appendChild(node);
	return { destroy: () => node.remove() };
}

const contextmenu_handler_1 = e => e.preventDefault();

function instance($$self, $$props, $$invalidate) {
	const omit_props_names = ["closeOnSelect","open","wrapperElement","anchorElement","menuElement"];
	let $$restProps = compute_rest_props($$props, omit_props_names);
	let { $$slots: slots = {}, $$scope } = $$props;
	let { closeOnSelect = true } = $$props;
	let { open = false } = $$props;
	let { wrapperElement = null } = $$props;
	let { anchorElement = null } = $$props;
	let { menuElement = null } = $$props;
	const dispatch = createEventDispatcher();
	let menu;
	let menuPosition = { x: 0, y: 0 };
	let mousePosition = { x: 0, y: 0 };

	async function handleContextMenu({ clientX, clientY }) {
		$$invalidate(0, open = true);
		$$invalidate(10, mousePosition = { x: clientX, y: clientY });
	}

	function handleEscapeKey({ key }) {
		if (key === "Escape") $$invalidate(0, open = false);
	}

	setContext("closeFlyout", event => {
		dispatch("select");
		if (closeOnSelect) $$invalidate(0, open = false);
	});

	function contextmenu_handler(event) {
		bubble.call(this, $$self, event);
	}

	function menuflyoutsurface_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			menu = $$value;
			$$invalidate(4, menu);
		});
	}

	function menuflyoutsurface_element_binding(value) {
		menuElement = value;
		$$invalidate(2, menuElement);
	}

	function div_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			anchorElement = $$value;
			$$invalidate(1, anchorElement);
		});
	}

	const outermousedown_handler = () => $$invalidate(0, open = false);

	function div_binding_1($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			wrapperElement = $$value;
			$$invalidate(3, wrapperElement);
		});
	}

	$$self.$$set = $$new_props => {
		$$props = assign(assign({}, $$props), exclude_internal_props($$new_props));
		$$invalidate(8, $$restProps = compute_rest_props($$props, omit_props_names));
		if ('closeOnSelect' in $$new_props) $$invalidate(9, closeOnSelect = $$new_props.closeOnSelect);
		if ('open' in $$new_props) $$invalidate(0, open = $$new_props.open);
		if ('wrapperElement' in $$new_props) $$invalidate(3, wrapperElement = $$new_props.wrapperElement);
		if ('anchorElement' in $$new_props) $$invalidate(1, anchorElement = $$new_props.anchorElement);
		if ('menuElement' in $$new_props) $$invalidate(2, menuElement = $$new_props.menuElement);
		if ('$$scope' in $$new_props) $$invalidate(18, $$scope = $$new_props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*open*/ 1) {
			$: dispatch(open ? "open" : "close");
		}

		if ($$self.$$.dirty & /*menu, menuElement*/ 20) {
			$: if (menu && tabbable(menuElement).length > 0) tabbable(menuElement)[0].focus();
		}

		if ($$self.$$.dirty & /*anchorElement, mousePosition, menuPosition*/ 1058) {
			$: if (anchorElement) {
				const { width, height } = anchorElement.getBoundingClientRect();
				$$invalidate(5, menuPosition.x = Math.min(window.innerWidth - width, mousePosition.x), menuPosition);

				$$invalidate(
					5,
					menuPosition.y = mousePosition.y > window.innerHeight - height
					? $$invalidate(10, mousePosition.y -= height, mousePosition)
					: mousePosition.y,
					menuPosition
				);

				if (menuPosition.y < 0) $$invalidate(5, menuPosition.y = 0, menuPosition);
			}
		}
	};

	return [
		open,
		anchorElement,
		menuElement,
		wrapperElement,
		menu,
		menuPosition,
		handleContextMenu,
		handleEscapeKey,
		$$restProps,
		closeOnSelect,
		mousePosition,
		slots,
		contextmenu_handler,
		menuflyoutsurface_binding,
		menuflyoutsurface_element_binding,
		div_binding,
		outermousedown_handler,
		div_binding_1,
		$$scope
	];
}

class ContextMenu extends SvelteComponent {
	constructor(options) {
		super();

		init(
			this,
			options,
			instance,
			create_fragment,
			safe_not_equal,
			{
				closeOnSelect: 9,
				open: 0,
				wrapperElement: 3,
				anchorElement: 1,
				menuElement: 2
			},
			add_css
		);
	}
}

export default ContextMenu;